### ISSUE TITLE
Suggestion opens browser?

### ISSUE THREAD

**Issue by DenisVCode** [dialogflow/dialogflow-fulfillment-nodejs#17]
Hi, in Actions on Google library this was possible:
`app.ask(app.buildRichResponse()
            .addSimpleResponse('Example')
            .addSuggestionLink('Suggestion Link', 'https://assistant.google.com/') // After clicking it would open browser
          );`

I couldn't find any way how to do this here. Did I missed something or is it just not supported?
Thanks for reply.

**Comment by matthewayne** [comment]
Hello! Thanks for trying out the library. The omission of Actions on Google-specific feature support like [link suggestion links/link out suggestions](https://developers.google.com/actions/assistant/responses#suggestion_chip) is intentional. If you'd like to use Actions on Google specific features you have two options

a) use the Actions on Google v2 alpha client library integration as demonstrated in the code snippet below (see [this sample](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/tree/master/samples/actions-on-google) for more context/setup)
```
let conv = agent.conv();
conv.ask(new LinkOutSuggestion({name: 'Website', url: 'https://assistant.google.com'}))
```

b) Use the Actions on Google library to fulfill you Dialogflow agent.  There are [many samples demonstrating this on the Action on Google Github org](https://github.com/actions-on-google?utf8=%E2%9C%93&q=dialogflow&type=&language=javascript).


Option A is likely better if you'd like to fulfill multiple Dialogflow integrations at the same time (i.e. the Google Assistant, Slack and Facebook Messenger) and Option B is likely better if you plan to only use the Actions on Google Dialogflow integration.
