### ISSUE TITLE
Node version incompatible with Google Cloud functions

### ISSUE THREAD

**Issue by vincentlaucy** [dialogflow/dialogflow-fulfillment-nodejs#19]
Is the module designed to be run on Google Cloud Functions?

I wonder the module has requirement on the node engine to be [~8.0](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/package.json#L12)

While the Node version of (publicly available) Google Cloud functions is `v6.11.5` if I understand correctly?
https://cloud.google.com/functions/docs/writing/

**Comment by matthewayne** [comment]
Hi, thanks for taking a look at the library!  I initially had the node version at ~8.0 due to the use of some Node 8-only features use for testing the library but not the library itself.  The library itself has always been compatible with Google Cloud functions and Node 6+.  I've since removed the Node 8 only features and updated the package.json accordingly
