### ISSUE TITLE
Currently there are no methods to getPermission for name, location etc.

### ISSUE THREAD

**Issue by maazonline** [dialogflow/dialogflow-fulfillment-nodejs#20]

**Comment by matthewayne** [comment]
Hello! Thanks for trying out the library.  The omission of getPermission methods and other Actions on Google specific methods is intentional.  If you'd like to use Actions on Google specific features you have two options

a) use the Actions on Google v2 alpha client library integration [as demonstrated in this sample](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/tree/master/samples/actions-on-google) (more info on the Actions on Google v2 alpha are [here](https://github.com/actions-on-google/actions-on-google-nodejs/tree/v2.0.0-alpha))
--OR--
b) Use the Actions on Google library to fulfill you Dialogflow agent.  There are [many samples demonstrating this on the Action on Google Github org](https://github.com/actions-on-google?utf8=%E2%9C%93&q=dialogflow&type=&language=javascript).

Option A is likely better if you'd like to fulfill multiple Dialogflow integrations at the same time (i.e. the Google Assistant, Slack and Facebook Messenger) and Option B is likely better if you plan to only use the Actions on Google Dialogflow integration.
