### ISSUE TITLE
[Bug] Diaflow can not connect with firebase

### ISSUE THREAD

**Issue by kingame96** [dialogflow/dialogflow-fulfillment-nodejs#221]
I have a fulfillment inline editor code
```
'use strict';
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();
const { 
  dialogflow,
  BasicCard,
  BrowseCarousel,
  BrowseCarouselItem,
  Button,
  Carousel,
  Image,
  LinkOutSuggestion,
  List,
  MediaObject,
  Suggestions,
  SimpleResponse,
  Table  } = require('actions-on-google');
const intentSuggestions = [
  'Control',
  'Get Status',
  'light on',
  'light off',
  'light status',
  'fan on',
  'fan off',
  'fan status',
];
const app = dialogflow();
app.intent('Input_Welcome', (conv) => {
  conv.ask(`Welcome, How can I help?`);
  conv.ask(new Suggestions(intentSuggestions));
});
 
app.intent('device',(conv, { devices, status }) => {
  return admin.database().ref(`/ESP8266/${devices}/value`).set(status)
    .then(snapshot => {
      conv.ask(`OK, switching ${devices} ${status}. Do you want more?`);
      conv.ask(new Suggestions(intentSuggestions));
    })
    .catch(error => console.error(error)); // Added a catch block
});
exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);
```
 When i deploy it, i have an error in function logs "dialogflowFirebaseFulfillment
Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail "(1)
. When i call "light on" in simulator to trigger "device" intent  , i have an error " xxx left the conservation" and function logs " FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com ...."(2) .
If I remove this code 
```
return admin.database().ref().set()
.then(snapshot => {
});
```
the simulator is ok ( but still have the error (1)).
About three months ago, I deployed this code and it all okay.
I read the changelogs and docs but cant find how to fix it.
Pls help me what wrong with firebase.
I use realtime database.

This is my pakage.json
```
{
  "name": "dialogflowFirebaseFulfillment",
  "description": "This is the default fulfillment for a Dialogflow agents using Cloud Functions for Firebase",
  "version": "0.0.1",
  "private": true,
  "license": "Apache Version 2.0",
  "author": "Google Inc.",
  "engines": {
    "node": "8"
  },
  "scripts": {
    "start": "firebase serve --only functions:dialogflowFirebaseFulfillment",
    "deploy": "firebase deploy --only functions:dialogflowFirebaseFulfillment"
  },
  "dependencies": {
    "actions-on-google": "^2.2.0",
    "firebase-admin": "^5.13.1",
    "firebase-functions": "^2.0.2",
    "dialogflow": "^0.6.0",
    "dialogflow-fulfillment": "^0.5.0"
  }
}
```
I contacted with firebase support and he recommend me open a bug. Sorry for my bad english !!
![image](https://user-images.githubusercontent.com/37318114/53462657-2e129600-3a77-11e9-8916-62bb1042d359.png)
![image](https://user-images.githubusercontent.com/37318114/53462685-4a163780-3a77-11e9-88e3-c49df8472b06.png)
![image](https://user-images.githubusercontent.com/37318114/53462702-5a2e1700-3a77-11e9-9df7-180cf3036931.png)
![image](https://user-images.githubusercontent.com/37318114/53462768-8a75b580-3a77-11e9-92af-4a6065ca2179.png)
![image](https://user-images.githubusercontent.com/37318114/53462986-35866f00-3a78-11e9-9ae4-9bd8d7e5a3fa.png)

**Comment by nathanjliu** [comment]
To make calls to external network requests you need to be on the Flame or Blaze plans of Firebase. You are on the free Spark plan. This may or may not be a cause of your issue.

**Comment by sarahdwyer** [comment]
It seems you may be confusing the Actions on Google client library with the Dialogflow-Fulfillment library, i.e. the latter being the place where you are posting your issue. However, you are building an Action and using the Actions on Google client library. I'd check out the available [samples](https://github.com/actions-on-google). 

The issue is with your package.json file because you are using the Dialogflow-Fulfillment's boilerplate dependencies package file, instead it should be: 

```
{
  "name": "your-action-app",
  "description": "This is your Action's webhook",
  "version": "0.0.1",
  "private": true,
  "license": "Apache Version 2.0",
  "author": "Google Inc.",
  "engines": {
    "node": "8"
  },
  "scripts": {
    "lint": "eslint --fix \"**/*.js\"",
    "start": "firebase serve --only functions",
    "deploy": "firebase deploy --only functions",
    "test": "npm run lint"
  },
  "dependencies": {
    "actions-on-google": "^2.0.0",
    "firebase-admin": "^5.11.0",
    "firebase-functions": "^1.0.0"
  },
  "devDependencies": {
    "eslint": "^4.19.0",
    "eslint-config-google": "^0.9.1"
  }
}
```

**Comment by kingame96** [comment]
> It seems you may be confusing the Actions on Google client library with the Dialogflow-Fulfillment library, i.e. the latter being the place where you are posting your issue. However, you are building an Action and using the Actions on Google client library. I'd check out the available [samples](https://github.com/actions-on-google).
> 
> The issue is with your package.json file because you are using the Dialogflow-Fulfillment's boilerplate dependencies package file, instead it should be:
> 
> ```
> {
>   "name": "your-action-app",
>   "description": "This is your Action's webhook",
>   "version": "0.0.1",
>   "private": true,
>   "license": "Apache Version 2.0",
>   "author": "Google Inc.",
>   "engines": {
>     "node": "8"
>   },
>   "scripts": {
>     "lint": "eslint --fix \"**/*.js\"",
>     "start": "firebase serve --only functions",
>     "deploy": "firebase deploy --only functions",
>     "test": "npm run lint"
>   },
>   "dependencies": {
>     "actions-on-google": "^2.0.0",
>     "firebase-admin": "^5.11.0",
>     "firebase-functions": "^1.0.0"
>   },
>   "devDependencies": {
>     "eslint": "^4.19.0",
>     "eslint-config-google": "^0.9.1"
>   }
> }
> ```

Ok i fixed it. That's great. Many thanks for your help !!

**Comment by khoa21214475** [comment]
I have the same fulfillment inline editor code:

//--------------------------------------------------------------------//
'use strict';
 
//Khai báo thư viện để kết nối triển khai code lên firebase-functions
const functions = require('firebase-functions');
 
//Khai báo thư viện để kết nối với Firebase Realtime Database
const admin = require('firebase-admin');
admin.initializeApp({
  credential: admin.credential.applicationDefault(),
  databaseURL: 'https://nodemculed-d7408.firebaseio.com'
});
// Khai báo các dịch vụ được hỗ trợ bởi actions-on-google
const { 
  dialogflow,
  BasicCard,
  BrowseCarousel,
  BrowseCarouselItem,
  Button,
  Carousel,
  Image,
  LinkOutSuggestion,
  List,
  MediaObject,
  Suggestions,
  SimpleResponse,
  Table  } = require('actions-on-google');
 
//Khai báo các gợi ý dành cho người dùng (tối đa 8 gợi ý)
const intentSuggestions = [
  'Control',
  'Get Status',
  'light on',
  'light off',
  'light status',
  'fan on',
  'fan off',
  'fan status',
];
 
 
// Tạo instance đặt tên là "app" để tương tác với dialogflow.
const app = dialogflow();
 
 
// Xử lý các Dialogflow intents.
app.intent('Input_Welcome', (conv) => {
  conv.ask(`Welcome 222, How can I help?`);
  conv.ask(new Suggestions(intentSuggestions));
});
app.intent('Control_Devices',(conv, { devices, status }) => {
  return admin.database().ref(`/ESP8266/${devices}/value`).set(status)
    .then(function(snapshot) {
      conv.ask(`OK, switching ${devices} ${status}. Do you want more?`);
      conv.ask(new Suggestions(intentSuggestions));
    });		
});
 
 
app.intent('Get_Status_Devices',(conv, { devices }) => {
	return admin.database().ref(`/ESP8266/${devices}`).once("value")
		.then(function(snapshot) {
			var sta = snapshot.child("value").val();
      		//var sta = "on";
			conv.ask(`${devices} status is ` + sta + `. Do you want more?`);
			conv.ask(new Suggestions(intentSuggestions));
		});			
  });
 exports.dialogflowFirebaseFulfillment = functions.https.onRequest(app);

//-----------------------------------------------------------------------------------------//
But i have a problem when I test in Actions on Google:
"MalformedResponse
Failed to parse Dialogflow response into AppResponse because of invalid platform response: Could not find a RichResponse or SystemIntent in the platform response for agentId: 4cbca294-9872-4dbc-86ee-daf947e3962e and intentId: 6974f665-acb9-4a8f-934a-e540bce4eab4. WebhookStatus: code: 4 message: "Webhook call failed. Error: DEADLINE_EXCEEDED." .."

How can i fix this problem ? Please help me!

**Comment by holdinvestors-don** [comment]
> > It seems you may be confusing the Actions on Google client library with the Dialogflow-Fulfillment library, i.e. the latter being the place where you are posting your issue. However, you are building an Action and using the Actions on Google client library. I'd check out the available [samples](https://github.com/actions-on-google).
> > The issue is with your package.json file because you are using the Dialogflow-Fulfillment's boilerplate dependencies package file, instead it should be:
> > ```
> > {
> >   "name": "your-action-app",
> >   "description": "This is your Action's webhook",
> >   "version": "0.0.1",
> >   "private": true,
> >   "license": "Apache Version 2.0",
> >   "author": "Google Inc.",
> >   "engines": {
> >     "node": "8"
> >   },
> >   "scripts": {
> >     "lint": "eslint --fix \"**/*.js\"",
> >     "start": "firebase serve --only functions",
> >     "deploy": "firebase deploy --only functions",
> >     "test": "npm run lint"
> >   },
> >   "dependencies": {
> >     "actions-on-google": "^2.0.0",
> >     "firebase-admin": "^5.11.0",
> >     "firebase-functions": "^1.0.0"
> >   },
> >   "devDependencies": {
> >     "eslint": "^4.19.0",
> >     "eslint-config-google": "^0.9.1"
> >   }
> > }
> > ```
> 
> Ok i fixed it. That's great. Many thanks for your help !!

>Sorry, Can you tell more details? I followed the lines, it did not work. Thanks.
