### ISSUE TITLE
Guidance for implementing Carousel

### ISSUE THREAD

**Issue by Savjee** [dialogflow/dialogflow-fulfillment-nodejs#25]
Hi!

For me this library is great because it automatically "translates" rich responses to the format that individual platforms require.

I would like to extend this library to also support Carousels.
Am I correct in assuming that all I have to do is create a new type of RichResponse and change the `getV1ResponseObject_` and `getV2ResponseObject_` methods?

Or do you don't want to add features that only work for certain platforms and not all 14 supported ones?

**Comment by eisenjulian** [comment]
Agree. There seems to be an example here but I couldn't make it work. https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/actions-on-google/functions/index.js

The fact that the carousel cards are in an object (that doesn't have ordered keys) instead of an array is pretty suspicious. The same thing goes for Lists, ended up going to the default actions on google package.

**Comment by matthewayne** [comment]
This library is best if you are interested in multiple integrations or aren't sure what integration you plan on using this library is the best place to start.

If you're using Node.js Dialogflow fulfillment and are only interested in the Actions on Google integration the actions-on-google npm module is the the best place to start and has first class support for Actions on Google construct like carousels.

Implementing cross-platforms carousels is currently out of scope for this library as each different supports platforms handles carousels very differently.

For how to implement carousels with this library via the actions-on-google npm module integration or custom payloads please see https://github.com/dialogflow/dialogflow-fulfillment-nodejs/issues/36
