### ISSUE TITLE
How to Store user details?

### ISSUE THREAD

**Issue by Ashwin-Kapes** [dialogflow/dialogflow-fulfillment-nodejs#74]
How to store any user detail for **1) current session** and **2) Permanently**.

All I know that in Actions on google **conv.user.storage** is available. But what if Messenger Bot is used.

**Comment by olhapi** [comment]
You need to use some persistent database to store data.

**Comment by Ashwin-Kapes** [comment]
@olhapi For sure I'll use any DB but how to manipulate that data. For example user sends 5 different messages then I'm getting 5 different JSON at Backend. So I have to extract parameters/queryText from each JSON and save to DB. That means 5 INSERT calls to DB. Is there any way I can collect all conversation data in session or temporary memory and once conversation is over then save entire conversation data to DB.

**Comment by olhapi** [comment]
Well, actually you don't need to get a JSON from dialogflow every time a user sent a message, unless you use webhook for slot filling. In that case you indeed need to store temporary data in db.

In case you don't need slot filling you just collect all required parameters on dialogflow side and then send them all at once to our webhook.

**Comment by matthewayne** [comment]
For the current session you can use the parameters in [a context](https://dialogflow.com/docs/reference/api-v2/rest/Shared.Types/Context) for simple key-value, just make sure to set the lifetime to a high number and increase it if the lifetime count gets low. Contexts last the entirety of a session if the lifetime is kept above zero.

For permanent storage you can use any database solution in fulfillment you like.  There is a sample that integrates Dialogflow with Firebase's Firestore database here: https://github.com/dialogflow/fulfillment-firestore-nodejs

**Comment by alexedtionweb** [comment]
> @olhapi For sure I'll use any DB but how to manipulate that data. For example user sends 5 different messages then I'm getting 5 different JSON at Backend. So I have to extract parameters/queryText from each JSON and save to DB. That means 5 INSERT calls to DB. Is there any way I can collect all conversation data in session or temporary memory and once conversation is over then save entire conversation data to DB.

Did you find the right solution?
To resolve this I think  we need to create a handler for users messages and then send to dialogflow (via dialogflow client) and receive that response to answer the user. Another thing is within the application we can set the session ID and store in a database when its pertinent to save (Own logic), like firebase, MySQL or MongoDb (whatever GCP store services or third parts), this could help within the 20min context life and to store all user data (intents that uses webhook or not).

**Comment by praveenptl71** [comment]
I have created following flow : 
**Intent-1**) What is your name? **parameters** : username

**Intent-2)** What is your contact no? **parameters** : phone_number

**Intent-3)** inquiry type? **parameters** : inquiry_type

**Intent-4)** mfg-unit? **parameters** : mfg_unit

**Intent-5**) priority? **parameters** : priority

Now i want all parameter in last intent response so that i can add these parameters value in back-end

**Comment by Shagunkalra** [comment]
If you want parameter in the last response and then use it in for the database, you can use (context.get) function instead of parameters.var

**Comment by andipp21** [comment]
> If you want parameter in the last response and then use it in for the database, you can use (context.get) function instead of parameters.var

Did you have some example?
I really confused about this problem.

**Comment by bpbutti** [comment]
> > If you want parameter in the last response and then use it in for the database, you can use (context.get) function instead of parameters.var
> 
> Did you have some example?
> I really confused about this problem.

Suppose you have 3 conversation nodes (A, B, C), where A is the welcome intent, B is some step in the middle, and C is the goodbye intent. And suppose you are gathering the variables "user_name" and "phone_number" during the conversation.

What I do to save all the parameters is the following:

- Set input and output contexts in the conversation nodes:
  - Node A set "output context": global_context
  - Node B set "input context": global_context and "output context": global_context with lifespan = 1
  - Node C set "input context": global_context and "output context": global_context with lifespan = 1

This can be done on the Graphical Interface
![image](https://user-images.githubusercontent.com/11468260/75637096-d5825580-5c02-11ea-899c-cfe3c9279f38.png)

- Enable webhook call for node C (Turn on the option "Enable webhook call for this intent")

![image](https://user-images.githubusercontent.com/11468260/75637133-2d20c100-5c03-11ea-878e-72b70206749b.png)

- Use the following on the intent handler:

```js
function intent_C_handler(agent) {
    // Get parameters
    const global_context = agent.context.get('global_context');
    const user_name = global_context.parameters.user_name;
    const phone_number = global_context.parameters.phone_number;

    // Here you do something to save these variables to a persistent database
 }
```

You can extend this to any numbers of conversation nodes and parameters

* as a side note: Update the libraries on the packge.json if you are using the fulfillment inline editor, as it might not work otherwise

![image](https://user-images.githubusercontent.com/11468260/75637223-d071d600-5c03-11ea-9215-b574197c7ec0.png)
